FROM node:18.16.0 AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --production --silent
COPY . .
RUN npm run build


FROM node:18-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/package*.json /usr/src/app
COPY --from=builder /usr/src/app/node_modules /usr/src/app/node_modules
COPY --from=builder /usr/src/app/dist /usr/src/app/dist

ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "run", "serve"]